### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by AnimeniacSimey** [0x000cb/otc#1]
Often I'll be in a game and I'll try to shoot someone, then boom. Game crashes. Suggested fix? Or is this because of the recent update?

**Comment by 0x000cb** [comment]
What configuration are you using? Legit / Rage?

**Comment by AnimeniacSimey** [comment]
Using a legit config, have tried rage but not used it for long. I see you have a new release now! Thanks.

**Comment by 0x000cb** [comment]
All legit configurations causes crash. (I suspect this is a netvar that has been updated). In any case, I’ll try to figure out what’s wrong and update as soon as possible.

**Comment by AnimeniacSimey** [comment]
Thanks so much!

**Comment by 0x000cb** [comment]
Solved. Fix in new update.

**Comment by AnimeniacSimey** [comment]
:D

**Comment by xSkuLz** [comment]
When will you release the fixed version mate?
