### ISSUE TITLE
After I inject it, CS:GO is gettting frozen

### ISSUE THREAD

**Issue by BloodStainsTR** [0x000cb/otc#101]
After I inject, the game get stuck at black screen, here is the text file created by OTC:
[otc_latest.txt](https://github.com/0x000cb/otc/files/4734433/otc_latest.txt) 
Multi-threaded rendering is opened and `disable d3x9` startup option is enabled

**Comment by TooneyTurkey** [comment]
when did you last install otc

**Comment by 0x000cb** [comment]
Use last version otc before create issue.
