### ISSUE TITLE
Skin Changer Bugged

### ISSUE THREAD

**Issue by jacobred132** [0x000cb/otc#105]
Not entirely sure if this is an issue caused by me or if otc skin changer broke in the last release, only my glove skin updates and rarely the gun I'm holding when i load my skin.cfg it will show the skin i picked for that aswell.

**Comment by DoxyPS** [comment]
not sure what this means but just drop your gun and buy again. its a issue with 50% of skin changers.

**Comment by jacobred132** [comment]
I did that and it only displays the skin name and doesn't show the skin on the weapon.

**Comment by 0x000cb** [comment]
Can you show it on vid?

**Comment by jacobred132** [comment]
https://youtu.be/5zlkmP8bMUQ

**Comment by 0x000cb** [comment]
Probably can be caused by give method. Try just buy weapon.

**Comment by jacobred132** [comment]
I've done both methods and still the same problem, buying them or giving them in console. Idm making another vid showing me buying instead if you need it.

**Comment by 0x000cb** [comment]
Yeah, show pls in vid.

**Comment by jacobred132** [comment]
Do you want MM or will a bot game be enough?

**Comment by jacobred132** [comment]
https://youtu.be/56MZAEM8nwI

Added both since you didn't answer.

**Comment by jacobred132** [comment]
Hope i can help by making this known even if it's a 1 time bug or just limited to me, Thanks for updating the cheat every update and trying to patch small things like this man.

**Comment by 0x000cb** [comment]
Interesting. Where you find this cfg?

**Comment by jacobred132** [comment]
Just made it in the menu so i have no clue why it's like this.

**Comment by jacobred132** [comment]
Haven't tested it on other PC's so could be the cfg.

[skins.zip](https://github.com/0x000cb/otc/files/4741321/skins.zip)

**Comment by 0x000cb** [comment]
Hm, just for me all works fine. Try this.
[skins.zip](https://github.com/0x000cb/otc/files/4741323/skins.zip)

**Comment by jacobred132** [comment]
Using that one fixed it, Thanks for the help and sorry if i wasted your time.

**Comment by 0x000cb** [comment]
Np. Possible reason - you just use newest skins.
