### ISSUE TITLE
Game crashes at "random" moments

### ISSUE THREAD

**Issue by TheGuardian226** [0x000cb/otc#106]
My game will crash 10 minutes into a game, sometimes with almost nothing happening. This seems to occur sometimes when I open the config menu, or press "esc". 

Crashing also happens when switching to another map. For example, after a deathmatch ends the map will reset and take you to a loading screen. 

I don't think this is important but I previously used the Xenos injector (I believe it can be found on unknowncheats) and it couldn't even inject with an error code: 0xC000010E. After using another injector, it worked.

**Comment by 0x000cb** [comment]
Try use process hacker for inject. If after use process hacker you still have this error, please re-create issue with video.

**Comment by TheGuardian226** [comment]
I checked my minidump in windbg and found out that it was not because of otc, but because of a corrupted file: tier0.dll. A simple delete fixed the issue.
