### ISSUE TITLE
Log

### ISSUE THREAD

**Issue by SinsF** [0x000cb/otc#107]
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! PANIC !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

If you see this message: OTC cannot find a way out of the situation.
After information about the cause of the error, CSGO will be frozen.

----------- INFO ----------
Layer: 1.
Caused: Can't find offset. Signature: 55 8B EC 83 E4 F8 83 EC 70 6A 58.
----------------------------
Global variables: 
-----------------------------------------------------------
[SEGMENT] Module: 0x39680000
[SEGMENT] Allocation: 0x3C200000
-----------------------------------------------------------

Send this log to the developer or try connecting a debugger and find out what the problem is.
Bye.

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! PANIC !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by 0x000cb** [comment]
Redowload dll. Don't use beta build's.
