### ISSUE TITLE
Can overwatch see the ESP/Glow/Charms feature?

### ISSUE THREAD

**Issue by WilliamJiH** [0x000cb/otc#108]
I just got overwatch banned a few seconds ago. I'm playing quiet legit, aimbot fov: 1.1, smooth: 35%, hitscan everything except head, perfer head, rcs: 75%x 85%y. Triggerbot delay 300ms, No fake angles, fake lag or anti aim. Also I only have glow on. No auto strafe, no bhop. Quick stop and quick crouch on. And of course skin changer. That's all my features I have in the match. No crazy shots, most game have <1 KDA, most shots are body. My main weapon is awp, I had some headshots with deagle. I have no idea why I got convicted since I didn't HVH and always playing legit. So the only possible way that I could think is on the overwatch side they can see my glow?

**Comment by THEGHOSTSOLDIER** [comment]
Glow features like chams are only client-side. Overwatch viewers can't see any visual modifications that you make on your game. Try to reduce more FOV, increase smooth and improve your legit gameplay.

**Comment by 0x000cb** [comment]
Can't. You just don't know you play with legit cfg.
