### ISSUE TITLE
Вылет с FPS Monitor \ сrash with FPS Monitor

### ISSUE THREAD

**Issue by mpamop** [0x000cb/otc#109]
После инжекта otc с запущенным FPS Monitor ничего не происходит, но если зайти в игру, крашится из-за модуля fpsmon32.dll
Даже если включить монитор после инжекта, вылетает.
Использую версию FPS Monitor 4400

After the OTC injection, nothing happens with the FPS Monitor running, but if you go into the game, it crashes because of the module fpsmon32.dll
Even if you turn on the monitor after the injection, it crashes.
Use FPS Monitor 4400

**Comment by 0x000cb** [comment]
Используй net_graph 1 вместо FPS Monitor, или же найди замену. Сторонние программы я не поддерживаю.
