### ISSUE TITLE
How to change Username to Playername?

### ISSUE THREAD

**Issue by justAreadled** [0x000cb/otc#111]
How to change username of PC in watermark to playername - name in Steam profile?

**Comment by THEGHOSTSOLDIER** [comment]
Go to this line :
https://github.com/0x000cb/otc/blob/a9048317cdb6eb3076c4ea6e3adfa7d06e786008/OTC/dllmain.cpp#L92

Replace : 
getenv ("USERNAME") 
by
"YourSteamUsername"

Next time read the FAQ before asking a basic question and learncpp.com would be useful to know the code.

**Comment by 0x000cb** [comment]
learncpp dot com.

**Comment by StrictlyVox** [comment]
> Go to this line :
> https://github.com/0x000cb/otc/blob/a9048317cdb6eb3076c4ea6e3adfa7d06e786008/OTC/dllmain.cpp#L92
> 
> Replace :
> getenv ("USERNAME")
> by
> "YourSteamUsername"
> 
> Next time read the FAQ before asking a basic question and learncpp.com would be useful to understand the code.

uhh isn't 'getenv()' important?

**Comment by justAreadled** [comment]
No, you not understand me, how to make for any person a name was taken from the profile and has been written in watermark?

**Comment by StrictlyVox** [comment]
ask @0x000cb
