### ISSUE TITLE
New CSGO client update 

### ISSUE THREAD

**Issue by atxtn** [0x000cb/otc#116]
Game crashes after injecting DLL.

**Comment by Fishygru** [comment]
Thought this was just me.

**Comment by atxtn** [comment]
It's not a signature change this time

**Comment by 1nuki2** [comment]
And now what i can do

**Comment by Fishygru** [comment]
I think its because of the CS:GO update

**Comment by Fishygru** [comment]
> And now what i can do

You can always use some shitty free cheat for the time being like Deadly

**Comment by atxtn** [comment]
> > And now what i can do
> 
> You can always use some shitty free cheat for the time being like Deadly

lol prob gonna get VACed using that

**Comment by Fishygru** [comment]
> > > And now what i can do
> > 
> > 
> > You can always use some shitty free cheat for the time being like Deadly
> 
> lol prob gonna get VACed using that

true

**Comment by KakashiSeno** [comment]
the only thing we can make is to wait till 0x00 or sombody from his team update the file

**Comment by 0x000cb** [comment]
I will try to fix it today.
____
I am developing OTC alone. (If we are talking about reverse, fixes, or smth like this).

**Comment by atxtn** [comment]
> I will try to fix it today.
> 
> I am developing OTC alone. (If we are talking about reverse, fixes, or smth like this).

We appreciate you for all that you do :)

**Comment by streamliner0909** [comment]
thank you 0x000cb

**Comment by KakashiSeno** [comment]
0x000cb u are our hero 🥇

**Comment by HowToMakeFaceitAB** [comment]
> I will try to fix it today.
> 
> I am developing OTC alone. (If we are talking about reverse, fixes, or smth like this).

thank you man

**Comment by 0x000cb** [comment]
![image](https://user-images.githubusercontent.com/42978074/84352156-7bac0700-abc5-11ea-86ba-6eb4696d7b86.png)

Ok. Now tests....

**Comment by sammars99** [comment]
link

**Comment by streamliner0909** [comment]
> ![image](https://user-images.githubusercontent.com/42978074/84352156-7bac0700-abc5-11ea-86ba-6eb4696d7b86.png)
> 
> Ok. Now tests....

Would you mind sharing what the issue was? I'm currently learning C++ and would like to know more. It would be much appreciated.

**Comment by 0x000cb** [comment]
![image](https://user-images.githubusercontent.com/42978074/84352362-db0a1700-abc5-11ea-9389-1f57c21f16ed.png)

Seems like all worked. Bruh.

**Comment by apap04** [comment]
> > ![image](https://user-images.githubusercontent.com/42978074/84352156-7bac0700-abc5-11ea-86ba-6eb4696d7b86.png)
> > Ok. Now tests....
> 
> Would you mind sharing what the issue was? I'm currently learning C++ and would like to know more. It would be much appreciated.

let's wait until the new commit, we shall see...

**Comment by sammars99** [comment]
> ![image](https://user-images.githubusercontent.com/42978074/84352362-db0a1700-abc5-11ea-9389-1f57c21f16ed.png)
> 
> Seems like all worked. Bruh.

sure can you drop the dll sir
:D

**Comment by 1nuki2** [comment]
нихуя, ты че русский?

**Comment by 0x000cb** [comment]
Да. Точнее украинец. Отдай сало.

**Comment by 1nuki2** [comment]
нет у меня сала

**Comment by 1nuki2** [comment]
Когда выпустишь обнову?

**Comment by sammars99** [comment]
> Да. Точнее украинец. Отдай сало.

can you drop dll sir?

**Comment by 0x000cb** [comment]
5-10 min.

**Comment by Migzuuh** [comment]
> 5-10 min.

thx man <3

**Comment by Diwan1337** [comment]
А где можно будет найти? Я тут уже раза 3 заблудился=)

**Comment by 0x000cb** [comment]
Redownload release DLL.
____
Перекачайте длл с релиза.
