### ISSUE TITLE
new update how to change signature system

### ISSUE THREAD

**Issue by anyeyongheng** [0x000cb/otc#12]
how to change signature system 
![PJ%$98U`5N UEN)9U6EV5FQ](https://user-images.githubusercontent.com/46924287/78982446-b9080000-7b54-11ea-9f26-8a43e742e426.jpg)

**Comment by anyeyongheng** [comment]
how to update

**Comment by anyeyongheng** [comment]
where is it?

**Comment by anyeyongheng** [comment]
new version log 
1>C:\Users\34260\Desktop\q\OTC\OTC\Logger.cpp(5,41): error C4996: 'getenv': This function or variable may be unsafe. Consider using _dupenv_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
1>SegmentFramework.cpp
1>C:\Users\34260\Desktop\q\OTC\OTC\SegmentFramework.cpp(55,94): error C4996: 'getenv': This function or variable may be unsafe. Consider using _dupenv_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.

**Comment by 0x000cb** [comment]
I can’t imagine why you need such issues, but for the update you need only two versions of client_panorama, and IDA with sigmaker plugin. Look for the old signature in client_panorama_old and find the new one in client_panorama_new (Compare instructions, calls, etc.) 

---
Signatures you can find here: https://github.com/0x000cb/otc/blob/master/OTC/OTC/SegmentFramework.h#L78
