### ISSUE TITLE
compile

### ISSUE THREAD

**Issue by MumuWy** [0x000cb/otc#122]
hi i've a problem compiling the code.

Every time I try to build it I get lots of errors.
Could you help me please?

![file1](https://user-images.githubusercontent.com/61600859/84516752-843c3480-acce-11ea-8bab-89a49761c2ba.PNG)
![file2](https://user-images.githubusercontent.com/61600859/84516758-856d6180-acce-11ea-8876-5ace3c0383d8.PNG)
![file3](https://user-images.githubusercontent.com/61600859/84516759-856d6180-acce-11ea-869b-7dae4643409f.PNG)
![file4](https://user-images.githubusercontent.com/61600859/84516761-8605f800-acce-11ea-9b8a-ce3c4889872b.PNG)

**Comment by 0x000cb** [comment]
![image](https://user-images.githubusercontent.com/42978074/84517726-5a880b00-acd8-11ea-9a47-66f7e5486533.png)
