### ISSUE TITLE
Can't end process after crash

### ISSUE THREAD

**Issue by jalex45** [0x000cb/otc#127]
When some error occurs and CSGO crashes, I can't leave CSGO menu, open other application windows nor close CSGO by clicking cross. So only way to close process is restarting computer. Any other way to prevent that? (It doesn't give any notifications like "CSGO isn't responding.")

**Comment by Pikachumert58** [comment]
Rip OTC

**Comment by AntonDoil** [comment]
RIP

**Comment by 0x000cb** [comment]
Probably seems like OS issue. Try reinstall OS or connect debugger.
