### ISSUE TITLE
Thankl!But Where is the menu code

### ISSUE THREAD

**Issue by anyeyongheng** [0x000cb/otc#13]

**Comment by 0x000cb** [comment]
In segment. Open ida and reverse ot segment. This is not a onetap source code, it's loader for onetap segment. Please don't create issues like this.

**Comment by anyeyongheng** [comment]
Oh thank

**Comment by hol-low** [comment]
The menu code is securely stored on the Onetap secure mainframe server. Since it is of the highest value, there has to be so much protection around it.
