### ISSUE TITLE
cannot inject 

### ISSUE THREAD

**Issue by Trustlover** [0x000cb/otc#136]
| [~] Performing basic checks...
| [-] I cannot run OTC on the current version of Windows.
| [~] Please upgrade to 7 or 8, or 10. (PC build)
 but i am on windows 10

**Comment by DoxyPS** [comment]
what version of Windows 10 are you on?

(type winver into the search bar)

It should say something like 

Microsoft Windows
Version 1909  (OS Build 18363.900)

**Comment by Trustlover** [comment]
1809

**Comment by HowToMakeFaceitAB** [comment]
> 1809

update your windows

**Comment by 0x000cb** [comment]
Are you use server build win 10?

**Comment by Trustlover** [comment]
> Are you use server build win 10?

no WIN 10 pro

**Comment by 0x000cb** [comment]
Hm, seems like method doesn't run on you PC. I will try fix it in new update.
