### ISSUE TITLE
Crash due new csgo update

### ISSUE THREAD

**Issue by SadSonic** [0x000cb/otc#14]
Pls update the offsets thanks

**Comment by anyeyongheng** [comment]
not need update

**Comment by SadSonic** [comment]
> not need update

What do I do then to fix the crash?

**Comment by anyeyongheng** [comment]
Download the latest

**Comment by 0x000cb** [comment]
Maybe because index update. I will watch.

**Comment by 0x000cb** [comment]
Rage worked on valve servers. (Some issues with fakelag but you can just disable this). 
Legit work too. 

----
Closed. Thx for report.
