### ISSUE TITLE
1> Link: fatal error lnk1181: unable to open input file ".. \ LIBS \ objects \ hooklib. Object"

### ISSUE THREAD

**Issue by anyeyongheng** [0x000cb/otc#16]
why??

**Comment by 0x000cb** [comment]
It's on you Visual Studio or you just watch on github workflow?

**Comment by CKH0** [comment]
me2

**Comment by gosu821** [comment]
> It's on you Visual Studio or you just watch on github workflow?

its on visual when we download or clone github, but github worflow doesnt show...
i removed them, and still worrk

**Comment by playday3008** [comment]
Chill will be fixed today

**Comment by gosu821** [comment]
> Chill will be fixed today

I meant if some guys cant release maybe delete object when he open visual, i think its a little issue thx

**Comment by playday3008** [comment]
FIXED

**Comment by 0x000cb** [comment]
Solved. https://github.com/0x000cb/otc/pull/17. Thanks to @playday3008
