### ISSUE TITLE
TriggerBot / Backtrack crashing the game.

### ISSUE THREAD

**Issue by Sadlysius** [0x000cb/otc#20]
Hi, I'm not trying to whine doing this.
I just want to report a bug so it can potentially get fixed, thanks in advance :)

The game crashes if you die while holding TriggerBot button, also Backtrack causes random crashes sometimes (I can't identify when exactly, or what conditions cause this).

**Comment by 0x000cb** [comment]
This happens by accident (or rather, it depends on the ASLR). Crash calls up comparisons of the player matrix. I will try to decide.

**Comment by CKH0** [comment]
I have the same issue 
If I hold the key bind of triggerbot when I die. It will crash the game.
but I didn't have the backtracking issue

**Comment by 0x000cb** [comment]
Yes. When using TriggerBot / Backtrack in Legit, real magic happens inside. OT calls a bunch of functions over and over again. And one such function for computing vectors refused to work. This leads to crash.

![image](https://user-images.githubusercontent.com/42978074/79302619-90398f00-7ef5-11ea-9494-bb56cc0c0c02.png)

**Comment by 0x000cb** [comment]
Fixed. Expect update in the next 2 hours.

**Comment by 0x000cb** [comment]
Re-download OTC for get fix.

**Comment by Sadlysius** [comment]
Thanks a lot! I'm glad you could fix it

**Comment by 0x000cb** [comment]
New update. Re-Download for correctly work.
