### ISSUE TITLE
HookLib and Zydis don't load

### ISSUE THREAD

**Issue by souljaboycrankdat** [0x000cb/otc#21]
C:\Users\hugecock\Desktop\OTC\libs\libs\HookLib\HookLib\HookLib.vcxproj : error  : The project file could not be loaded. Could not find a part of the path 'C:\Users\hugecock\Desktop\OTC\libs\libs\HookLib\HookLib\HookLib.vcxproj'.  C:\Users\hugecock\Desktop\OTC\libs\libs\HookLib\HookLib\HookLib.vcxproj

C:\Users\hugecock\Desktop\OTC\libs\libs\Zydis\msvc\zydis\Zydis.vcxproj : error  : The project file could not be loaded. Could not find a part of the path 'C:\Users\hugecock\Desktop\OTC\libs\libs\Zydis\msvc\zydis\Zydis.vcxproj'.  C:\Users\hugecock\Desktop\OTC\libs\libs\Zydis\msvc\zydis\Zydis.vcxproj

reeeee how am i suppoused to add le epic junk code b1g paster is mad >:(

**Comment by 0x000cb** [comment]
Rly?

![image](https://user-images.githubusercontent.com/42978074/79303006-81071100-7ef6-11ea-8ab4-f680425ae1e2.png)
