### ISSUE TITLE
When dying your game crashes

### ISSUE THREAD

**Issue by xAl0n3** [0x000cb/otc#22]
Self explanatory by the title

Tried disabling esp, backtrack, trigger, localplayer esp etc
none of them seems to fix the problem

**Comment by 0x000cb** [comment]
Maybe it's caused by broken fix. I will test this.

**Comment by xAl0n3** [comment]
And theres this bug too that keeps bugging me out

When injecting in main menu it doesnt show the menu buttons and sliders etc
You have to open the console for them to show up, and yes I have added "-nod3d9ex" to my launch options and have enabled "Multicore rendering"

**Comment by xAl0n3** [comment]
![image](https://user-images.githubusercontent.com/43911142/79355188-04038800-7f46-11ea-807a-c48c4d9ce681.png)
Forgot to send the picture too

**Comment by 0x000cb** [comment]
Maybe injector issue. Or you use win 8.1 (yeah, it's can caused). 

----
Whatever, about main problem: 1 - 2 hours and new update.

**Comment by xAl0n3** [comment]
My friends use the same injector and the same OS (Windows 10 1909) and it works fine on their super computers.

**Comment by 0x000cb** [comment]
Looks like dependency issue.

**Comment by 0x000cb** [comment]
Updated. Re-Download.

**Comment by cptmacp** [comment]
@xAl0n3 

please stop using stupid injectors 

use process hacker 

dev uses process hacker and he won't provide support for any other injector

**Comment by xAl0n3** [comment]
@cptmacp Even with process hacker 2 it has the same issue.

**Comment by cptmacp** [comment]
try resetting csgo config and try

works fine for most of people

**Comment by playday3008** [comment]
> please stop using stupid injectors
> 
> use process hacker

Heh
