### ISSUE TITLE
TriggerBot crashes your game.

### ISSUE THREAD

**Issue by voltymtt** [0x000cb/otc#23]
When I scope with AWP and shoot with trigger my game crashes.

**Comment by 0x000cb** [comment]
Ok. I will test this.

**Comment by 0x000cb** [comment]
1 - 2 hours and new update.

**Comment by 0x000cb** [comment]
Updated. Re-download.

**Comment by Sadlysius** [comment]
Hi, should we download the release version? (last release 3 days ago)
Sorry for the dumb question and thanks a lot for your time fixing these bugs.

**Comment by 0x000cb** [comment]
I reupdate files in this release, so yep, just download.
