### ISSUE TITLE
New Source Missing Hooklib and Zydis 

### ISSUE THREAD

**Issue by SadSonic** [0x000cb/otc#27]
New Source Missing Hooklib and Zydis pls fix 

I don't know if is suppose to be missing but it doesn't load on visual studio so yea

**Comment by gosu821** [comment]
Read carefully readme

**Comment by YanderewareDev** [comment]
You need to download this repository by typing `git clone https://github.com/0x000cb/otc.git && cd otc && git submodule update --init --recursive` in cmd

**Comment by 0x000cb** [comment]
Awesome issue. Thanks for read FAQ. Have nice day.
