### ISSUE TITLE
Extended backtracking not working

### ISSUE THREAD

**Issue by GottaGetThat** [0x000cb/otc#29]
It just makes the history chams longer, but it doesnt actually let you hit those (only up to 200ms).
Making backtrack up to 400ms, will fix the problem, however it still adds +200ms to the current backtrack, which is annoying since you cant hit for that long.

**Comment by 0x000cb** [comment]
Thanks for the report. I will try to see what is wrong.

**Comment by GottaGetThat** [comment]
Also forgot to mention, that this isnt the loader's fault, its been happening ever since the crack got released.

**Comment by 0x000cb** [comment]
In this case, I can not help. You need to contact llama and ask about beatiful worked functions.
