### ISSUE TITLE
Severe inconsistencies in the loader code

### ISSUE THREAD

**Issue by hol-low** [0x000cb/otc#31]
Hello,

I have to say, I am utterly disgusted by the quality of this code, and my day is ruined. Could you imagine the disgust can come from just looking at a single function?

I am referring to this: https://github.com/0x000cb/otc/blob/master/OTC/cpp/utils/PanicUtils.cpp#L18

There is a total of 22 mentions of the ASCII newline character ('\n'), which is horribly inconsistent with the rest of the code. I don't think any competent developer could make such mistakes.

Instead, use the function that has the exact purpose of printing a newline character: https://github.com/0x000cb/otc/blob/master/OTC/cpp/runtime/Logger.cpp#L15

I believe, if my suggestions get implemented, the quality of code would rise significantly, and, as you can probably tell, the project really needs to improve in that direction.

Regards,
Vasiliy Hollow
Senior C++/C# developer

**Comment by es3n1n** [comment]
dat cod is shit men

**Comment by hol-low** [comment]
> dat cod is shit men

I don't think you had to use this kind of words to describe the situation the project is in, but I can't help but agree. If a single function could ruin a day, it surely would be the one I linked in the original post.

**Comment by es3n1n** [comment]
Instead of https://github.com/0x000cb/otc/blob/master/OTC/cpp/runtime/Logger.cpp#L15
You can use [this](https://github.com/0x000cb/otc/blob/master/OTC/cpp/frameworks/GameFramework.cpp#L4) function

**Comment by hol-low** [comment]
> Instead of https://github.com/0x000cb/otc/blob/master/OTC/cpp/runtime/Logger.cpp#L15
> You can use [this](https://github.com/0x000cb/otc/blob/master/OTC/cpp/frameworks/GameFramework.cpp#L4) function

While I can partially agree with you, using the function I linked would make much more sense in terms of project organisation and the general readability of the code. Since the function is located in the `Logger` class, it makes it much easier to understand where the newline character goes, and why.

The best way to tell if your code is readable enough or not, you need to imagine you know close to nothing about the project and/or the programming language in question. Does reading the lines one-by-one still paint the general picture of what the code is supposed to do? If the answer is yes, your code is readable enough.

**Comment by 0x000cb** [comment]
I am by no means a C++/ C developer. 
I have learned a little how to write C++, for write this loader. 
If you have suggestions for improving the code, you can use pull request.

p.s I am love JVM and OOP.
