### ISSUE TITLE
Newest build drops fps down significantly

### ISSUE THREAD

**Issue by CoolAsRice** [0x000cb/otc#32]
I downloaded the newest build of OTC but it's causing really large fps drops even when all settings are toggled to the lowest point. Also, legit aa sometimes reappears and then disappears in the menu.

**Comment by 0x000cb** [comment]
How many FPS do you lose? What version of OS? What are the characteristics of your pc?

--------
If the menu does not appear, the solutions are written in README. If it sometimes does not appear, do not turn on the menu when loading a map.

**Comment by CoolAsRice** [comment]
I'm losing about 50 fps going from 112 to around 60-75 frames. I'm running on Windows 10 with 8 GB of RAM, AMD 6 core processor, and a NVDIA GEFORCE GTX 960 graphics card. I usually get an average of 115 fps with my current CSGO settings.

**Comment by 0x000cb** [comment]
Pretty big FPS drop. I'll see why it happened. Thanks for the report.

**Comment by 0x000cb** [comment]
After long and lengthy tests, it turned out that the problem is mostly observed on Windows 10, with different configurations. The injector also sometimes influenced this. Perhaps you should try to change the injector, if it does not help - Windows.
