### ISSUE TITLE
cant compile 

### ISSUE THREAD

**Issue by sorrowvibez** [0x000cb/otc#35]
i did use the gitclone same thing

**Comment by 0x000cb** [comment]
How you clone? Pls show it on video.

**Comment by sorrowvibez** [comment]
okay

**Comment by sorrowvibez** [comment]
[2020-04-26 18-38-58.zip](https://github.com/0x000cb/otc/files/4535961/2020-04-26.18-38-58.zip)

**Comment by sorrowvibez** [comment]
here

**Comment by sorrowvibez** [comment]
@0x000cb

**Comment by 0x000cb** [comment]
Ok, now show how you open and compile this project.

**Comment by sorrowvibez** [comment]
k

**Comment by sorrowvibez** [comment]
[2020-04-26 18-55-48.zip](https://github.com/0x000cb/otc/files/4535990/2020-04-26.18-55-48.zip)

**Comment by sorrowvibez** [comment]
![image](https://user-images.githubusercontent.com/62300202/80314130-eeb51600-87ef-11ea-9859-29838e4a3016.png)
and now i get this shit

**Comment by sorrowvibez** [comment]
@0x000cb

**Comment by 0x000cb** [comment]
Ok, don't spam, you can use only one message.

**Comment by sorrowvibez** [comment]
aight ma bad

**Comment by 0x000cb** [comment]
Can you show ALL way from clone, to compile WITHOUT STOP REC pls?

**Comment by sorrowvibez** [comment]
aight im on ma slow pc rn so u can bear with me

**Comment by sorrowvibez** [comment]
[2020-04-26 19-10-19.zip](https://github.com/0x000cb/otc/files/4536010/2020-04-26.19-10-19.zip)
here u go 
@0x000cb

**Comment by 0x000cb** [comment]
Ok. Now show me the libs\objects\ folder. (Use screenshot pls)

**Comment by sorrowvibez** [comment]
![image](https://user-images.githubusercontent.com/62300202/80314759-a697f280-87f3-11ea-93ea-aedc8acf93da.png)
![image](https://user-images.githubusercontent.com/62300202/80314765-ae579700-87f3-11ea-85a5-9bf35ad421e1.png)
theres no object folder...

**Comment by sorrowvibez** [comment]
but y doe?

**Comment by 0x000cb** [comment]
![image](https://user-images.githubusercontent.com/42978074/80314812-62f5b680-87fc-11ea-8d37-bfa36a1b6c2c.png)
In configuration i see create folder script btw. Try create objects folder in OTC/libs/ and rebuild proj.

**Comment by 0x000cb** [comment]
Maybe you $ProjectDir broken, idk.

**Comment by sorrowvibez** [comment]
![image](https://user-images.githubusercontent.com/62300202/80314870-7a30a600-87f4-11ea-87e6-d871bcd7c001.png)
 here?

**Comment by 0x000cb** [comment]
Yes. Here. And check $ProjectDir path.

**Comment by sorrowvibez** [comment]
how do i do that lol

**Comment by sorrowvibez** [comment]
![image](https://user-images.githubusercontent.com/62300202/80314922-d398d500-87f4-11ea-9bc7-36f536b7ade9.png)
?

**Comment by sorrowvibez** [comment]
can you give me the source with the objects folder in it?

**Comment by 0x000cb** [comment]
Stop. Working Draft VS? Whatever, create folder and rebuild.

**Comment by sorrowvibez** [comment]
can you show me a video i dont understand lel

**Comment by 0x000cb** [comment]
ok.

**Comment by sorrowvibez** [comment]
cmon mane @0x000cb

**Comment by 0x000cb** [comment]
Btw it's look like only u side issue. Show me OTC project configuration.

https://www.youtube.com/watch?v=BDKxzSQg36o

**Comment by sorrowvibez** [comment]
![image](https://user-images.githubusercontent.com/62300202/80315766-fbd70280-87f9-11ea-89f6-373d077e57ab.png)
![image](https://user-images.githubusercontent.com/62300202/80315769-009bb680-87fa-11ea-9836-d295d938566e.png)
![image](https://user-images.githubusercontent.com/62300202/80315774-0f826900-87fa-11ea-8ff2-fe755faca6fc.png)
![image](https://user-images.githubusercontent.com/62300202/80315781-18733a80-87fa-11ea-998d-3b46f3e324f7.png)
![image](https://user-images.githubusercontent.com/62300202/80315784-1dd08500-87fa-11ea-804b-7943644927ad.png)

**Comment by sorrowvibez** [comment]
can you send me the one u built rn?

**Comment by sorrowvibez** [comment]
like upload it on anon files or anywhere u like?

**Comment by 0x000cb** [comment]
My build: https://anonfile.com/v8c1G4t1oa/OTC_dll

Try reinstall or update VS.

**Comment by sorrowvibez** [comment]
bruh not that like the full source

**Comment by 0x000cb** [comment]
k.

**Comment by 0x000cb** [comment]
https://anonfile.com/34gbGctfo0/builded_rar
