### ISSUE TITLE
untrusted ban

### ISSUE THREAD

**Issue by bakatame** [0x000cb/otc#36]
lots of people got untrusted ban, maybe cause by otc, can you check it?

**Comment by gtdani51** [comment]
lol, untrusted ban mostly caused by detected injectors and rarery by cheat itself

**Comment by 0x000cb** [comment]
>Can you check it
>Untrusted
Bye.

**Comment by 0x000cb** [comment]
(p.p.s Untrusted it's maybe NON VAC ban)
