### ISSUE TITLE
Questions about Segment.cpp

### ISSUE THREAD

**Issue by Tachyonator** [0x000cb/otc#39]
I have a few questions and hope that this is the right place for this...(I have not found a better one)

1.Is there a version of the segment.cpp in readable C++ language? Or is there only this binary file?
2.If you want to change something on this file, is it necessary to convert it into a readable 
programming language?
3.Can I convert the binary file into a readable C++ file without losing data?
4.Which program should I prefer to convert Segment.cpp into a readable language?

I hope that my questions are not misplaced here.

Best Regards

**Comment by cptmacp** [comment]
> I have a few questions and hope that this is the right place for this...(I have not found a better one)
> 
> 1.Is there a version of the segment.cpp in readable C++ language? Or is there only this binary file?
> 2.If you want to change something on this file, is it necessary to convert it into a readable
> programming language?
> 3.Can I convert the binary file into a readable C++ file without losing data?
> 4.Which program should I prefer to convert Segment.cpp into a readable language?
> 
> I hope that my questions are not misplaced here.
> 
> Best Regards

1. No ,OT source code was never release / cracked 
Nature of OT source is unknown 

2. We do hex and offset editing to change parts of the binary file 

3. Lol ,no .

4.maybe you should Google , " reverse engineering"

**Comment by 0x000cb** [comment]
1. Use Disassemblers for get pseudo C++ code.
2. Change smth in file - Asm patch's.
3. You can try reverse all binary and transfer pseudo to c++ project. (Pasta way)
4. IDA (with HexRays btw)/Ghidra/Cutter/Etc.

**Comment by Tachyonator** [comment]
Thank you very much!
