### ISSUE TITLE
Do we have to update offsets on our own?

### ISSUE THREAD

**Issue by AnimeniacSimey** [0x000cb/otc#4]
The game crashes on inject. Is there a way we can update offs?

**Comment by playday3008** [comment]
Modify `SegmentUtils.h` below offsets

**Comment by AnimeniacSimey** [comment]
I know, I found that. The issue is, none of them are listed. I'm not entirely sure if the order matters, but I  do know that signatures and netvars should be referred to seperately

**Comment by 0x000cb** [comment]
A new update is coming soon with Offset Updater and NOP Legit Void.  It remains only to wait a bit.

**Comment by AnimeniacSimey** [comment]
Do you have an approximate time for when?

**Comment by Baljeet-LIT** [comment]
?
