### ISSUE TITLE
The infamous gray box and/or invisible box 

### ISSUE THREAD

**Issue by django2121** [0x000cb/otc#40]
Hi so it was working just fine and all of a sudden im getting the infamous gray box I've tried everything :
1. Enabled Multicore rendering
2. Disable d3dx9 via launch commands
3. Disable AV/Defender
4. Opened console then injected via xenos injector
I was in the main menu when discord overlay appeared saying resolution too low for overlay to work at that time cheat was injected I clicked on that overlay and my pc froze, I had to restart it, after restarting the hack just wont inject properly, I've even deleted discord but nothing seems to work.
Here is the video if I load a match anyway after ignoring the gray box : https://imgur.com/a/Tq867Uj 
Please watch it so you can get a better idea of these weird glitchy black boxes after injecting too.
Any help would be greatly appreciated, thanks!

**Comment by 0x000cb** [comment]
Injector name?

**Comment by cptmacp** [comment]
please try using the process hacker 

also the fuck are those weird shapes on the monitor?

**Comment by django2121** [comment]
> Injector name?

I'm using xenox injector, it has been working fine for years, injected OTC for a couple weeks easily too.

**Comment by django2121** [comment]
> please try using the process hacker
> 
> also the fuck are those weird shapes on the monitor?

Alright I'll try process hacker
Those weird boxes only appear when I load a match after injecting the dll in main menu and getting the gray box.

**Comment by 0x000cb** [comment]
Ok. Show pls how you inject and settings (when u inject otc) on video.

**Comment by cptmacp** [comment]
@django2121 


inject the cheat first, dont inject in the match 

do on main menu

1. open csgo , open console

2. inject latest dll 

report back

**Comment by django2121** [comment]
> Ok. Show pls how you inject and settings (when u inject otc) on video.

[Video of injecting the dll](https://drive.google.com/file/d/1uDbm4cB50g0qjmxc9agwiVwVmAOxQi7k/view)

**Comment by django2121** [comment]
> Ok. Show pls how you inject and settings (when u inject otc) on video.

[Here is the video of injecting OTC](https://drive.google.com/file/d/18ZwJBxHxP2g1a9NH3woyR6GBJowY54sX/view?usp=sharing)

**Comment by django2121** [comment]
> @django2121
> 
> inject the cheat first, dont inject in the match
> 
> do on main menu
> 
> 1. open csgo , open console
> 2. inject latest dll
> 
> report back

sry man but tried in the video above still same problem :(

**Comment by 0x000cb** [comment]
Everything seems to be as it should, but a couple of points bother me.

1. What version of Windows?
2. Have you disabled any features in Windows itself for optimization?
3. Do you have redist msvc, directx11 and other standard library sets installed?
4. Until what point did everything work perfectly (What has changed in the operation of the OS itself)?

**Comment by django2121** [comment]
> Everything seems to be as it should, but a couple of points bother me.
> 
> 1. What version of Windows?
> 2. Have you disabled any features in Windows itself for optimization?
> 3. Do you have redist msvc, directx11 and other standard library sets installed?
> 4. Until what point did everything work perfectly (What has changed in the operation of the OS itself)?

1.  Windows 10 Pro (1809)
2. I have changed some power saving modes but OTC used to work just fine.
3. Yes standard library sets are installed with directx12
4. As I mentioned the problem surfaced when I was in main menu and discord overlay appeared telling me that game resolution is too small to work at that point OTC was injected and working, I clicked on that overlay and my pc froze, I had to restart it but after that its not working. I have uninstalled discord since then but still not working.

**Comment by 0x000cb** [comment]
I apologize for such a long answer. Possible reason: switching the power mode. Onetap is accessing the discordhook.dll library, but this cannot cause rendering failure. Perhaps some kind of malfunction in the system itself (or updating the drivers of the video card, etc.). The only thing I can advise (not knowing what exactly happened there) is to try to update all current drivers and update DirectX.
