### ISSUE TITLE
pls help me

### ISSUE THREAD

**Issue by tokyo666** [0x000cb/otc#41]
https://imgur.com/a/wdnoPG8 . 

D:\zak\otc-master\otc-master\OTC\libs\libs\Zydis\msvc\zydis\Zydis.vcxproj : error  : The project file could not be loaded. Could not find a part of the path 'D:\zak\otc-master\otc-master\OTC\libs\libs\Zydis\msvc\zydis\Zydis.vcxproj'.  D:\zak\otc-master\otc-master\OTC\libs\libs\Zydis\msvc\zydis\Zydis.vcxproj

**Comment by YanderewareDev** [comment]
Download project files using git, `git clone https://github.com/0x000cb/otc.git && cd otc && git submodule update --init --recursive `

**Comment by 0x000cb** [comment]
@YanderewareDev Thanks for answer. Closed.
