### ISSUE TITLE
OTC Does not inject

### ISSUE THREAD

**Issue by EEl-Chapo** [0x000cb/otc#43]
I recently reset my pc, downloaded cs go, ran the same working dll and injector that i used before the reset and cs go just ignores it. I have tried multiple otc.dlls and multiple different injectors so i know  its not the files. I even confirmed this with my laptop where the same dll and injector injected perfectly fine. 

Also, i have been able to inject a completely other cheat (orisis) that works like instantly after otc doesn't inject. I stated that because I don't think it was that the dll for otc was just taking it's time as i have waited for almost 15mins

**Comment by YanderewareDev** [comment]
Make sure that you have installed all C++ redistributables on your pc.

**Comment by EEl-Chapo** [comment]
i do have C++

**Comment by YanderewareDev** [comment]
Did you tried to compile it yourself?

**Comment by EEl-Chapo** [comment]
no, i have no experience with c++ but i do have it installed

**Comment by 0x000cb** [comment]
I already observed a similar problem, but it was not possible to find out what was the reason of the bug. Try using a debugger and track what is going on inside.

**Comment by cptmacp** [comment]
Try to use new config and disable and AV

Av = any sort of Antivirus and defender and disable dep also 

Use process hacker and enable console 

My friend has same issue ,it fixed with this
