### ISSUE TITLE
i have a question

### ISSUE THREAD

**Issue by tokyo666** [0x000cb/otc#44]
when to know that the OTC is outdated? pls answer me because i am using otc on my main. thank you <3

**Comment by 0x000cb** [comment]
It depends on what you mean by "outdated". If you mean undetect then OTC Loader does not guarantee you that.

**Comment by tokyo666** [comment]
ok thanks bro. bro for example if the otc is detected. how to patch it bro?
just press build otc? ty bro answering im new to this

**Comment by 0x000cb** [comment]
Use junk injector and try use vmp.

**Comment by 0FIRST0** [comment]
Hi, what should I do if Visual Studio cannot open the file in obj format and gives an error when compiling
