### ISSUE TITLE
Project Folder

### ISSUE THREAD

**Issue by MrMuyV2** [0x000cb/otc#45]
I got this Error.

https://prnt.sc/sbv21f

At least one project in the solution was not loaded properly. Details are displayed in the output window

**Comment by 0x000cb** [comment]
Show me "Ausgabefenster".

**Comment by MrMuyV2** [comment]
Ye wait

**Comment by MrMuyV2** [comment]
d:\Users\Florian Büro\Desktop\REVAYZ CLIENTS\otc-master\OTC\libs\libs\HookLib\HookLib\HookLib.vcxproj : error  : Die Projektdatei konnte nicht geladen werden. Ein Teil des Pfades "d:\Users\Florian Büro\Desktop\REVAYZ CLIENTS\otc-master\OTC\libs\libs\HookLib\HookLib\HookLib.vcxproj" konnte nicht gefunden werden.  d:\Users\Florian Büro\Desktop\REVAYZ CLIENTS\otc-master\OTC\libs\libs\HookLib\HookLib\HookLib.vcxproj


d:\Users\Florian Büro\Desktop\REVAYZ CLIENTS\otc-master\OTC\libs\libs\Zydis\msvc\zydis\Zydis.vcxproj : error  : Die Projektdatei konnte nicht geladen werden. Ein Teil des Pfades "d:\Users\Florian Büro\Desktop\REVAYZ CLIENTS\otc-master\OTC\libs\libs\Zydis\msvc\zydis\Zydis.vcxproj" konnte nicht gefunden werden.  d:\Users\Florian Büro\Desktop\REVAYZ CLIENTS\otc-master\OTC\libs\libs\Zydis\msvc\zydis\Zydis.vcxproj


thats the Error

**Comment by YanderewareDev** [comment]
Did you downloaded project using git, `git clone https://github.com/0x000cb/otc.git && cd otc && git submodule update --init --recursive
`

**Comment by MrMuyV2** [comment]
No i dont know, i just downloaded it

**Comment by YanderewareDev** [comment]
You need to use git to download the project, it will automaticlly download submodules (HookLib, Zydis) then and project will compile properly.

**Comment by MrMuyV2** [comment]
and how do i download it ?

**Comment by YanderewareDev** [comment]
Install git on your pc, and type command i quoted in cmd.

**Comment by MrMuyV2** [comment]
in my normal CMD or what? :D

**Comment by YanderewareDev** [comment]
Yes default windows cmd.

**Comment by MrMuyV2** [comment]
Okey :D

**Comment by MrMuyV2** [comment]
And i downloaded it now?

**Comment by MrMuyV2** [comment]
https://prnt.sc/sc646l

**Comment by YanderewareDev** [comment]
Now just go to the folder that it downloaded to and you should be ready to go.

**Comment by MrMuyV2** [comment]
Ye i just found it 👍 Thx

**Comment by MrMuyV2** [comment]
and thats now Onetap Crack?

**Comment by YanderewareDev** [comment]
No problem, you can close the issue now.

**Comment by MrMuyV2** [comment]
and now i get this error

3>LINK : fatal error LNK1181: Eingabedatei "libs\objects\HookLib.obj" kann nicht geöffnet werden.

**Comment by YanderewareDev** [comment]
It says that it cant open the file? I dont really know german so im asking.

**Comment by MrMuyV2** [comment]
yes

**Comment by YanderewareDev** [comment]
Do you have the `libs\objects\` folder?

**Comment by MrMuyV2** [comment]
no i dont have this :( 
https://prnt.sc/sc6acm

**Comment by YanderewareDev** [comment]
Try to create `objects` folder here.

**Comment by MrMuyV2** [comment]
just the folder?

**Comment by YanderewareDev** [comment]
Yes, create it and try to compile again.

**Comment by MrMuyV2** [comment]
https://prnt.sc/sc6cj2

**Comment by YanderewareDev** [comment]
Try to rebuild solution.

**Comment by MrMuyV2** [comment]
how?

**Comment by MrMuyV2** [comment]
still https://prnt.sc/sc6do4

**Comment by YanderewareDev** [comment]
Well, i see that someone already had similiar issue ( #35 ), @0x000cb shared the properly working otc project: https://anonfile.com/34gbGctfo0/builded_rar, try to download this project and it should compile without any problems.

**Comment by MrMuyV2** [comment]
Okey i will Inject it and i will see if it works :D

**Comment by MrMuyV2** [comment]
But is the Onetap Crack cheat right?

**Comment by YanderewareDev** [comment]
If you just want to download the compiled .dll, you can just go to `Release` section on github: https://github.com/0x000cb/otc/releases.

**Comment by YanderewareDev** [comment]
Yes, everything in this repository is related to onetap crack.

**Comment by MrMuyV2** [comment]
Now i get this error 
https://prnt.sc/sc6ju6

**Comment by YanderewareDev** [comment]
Isn’t it injector error?

**Comment by MrMuyV2** [comment]
Yes whats a good injector

**Comment by MrMuyV2** [comment]
xD Sorry fail upfff

**Comment by YanderewareDev** [comment]
Well, im using my own simple injector, but in project description it says that it is working with ProcessHacker.

**Comment by MrMuyV2** [comment]
Okey Thx

**Comment by YanderewareDev** [comment]
Im not really sure what happened that you cant compile it after cloning, i need to look deeper into that.

**Comment by MrMuyV2** [comment]
add me on discord: Bierwagen#3432

**Comment by YanderewareDev** [comment]
Problems are solved and everything is worling fine now, @MrMuyV2 forgot his passwors to github so im writing this for him. You can close the issue @0x000cb.

**Comment by 0x000cb** [comment]
@YanderewareDev thx for help. Closed.
