### ISSUE TITLE
Randomly crash but only sometime?

### ISSUE THREAD

**Issue by dapaster** [0x000cb/otc#46]
i get random crash sometimes when using otc ?

i did 
- Enable multi-threaded rendering
- d3d9ex

does injector also affect the performance of the cheat?

would you guys recommend me a good injector

**Comment by YanderewareDev** [comment]
You can try using ProcessHacker to inject dll and if you used any addons, try without them.

**Comment by 0x000cb** [comment]
Possible issues:
  - Performance.
  - Addon.
  - Injector.

Possible fix's:
  - Set all graphic settings to low. & Try clean-up system.
  - Contact with addon author for help with crash fix.
  - Use process hacker.

**Comment by dapaster** [comment]
thanks
