### ISSUE TITLE
New silent csgo update broke some things

### ISSUE THREAD

**Issue by SadSonic** [0x000cb/otc#47]
A silent csgo update I think that was yesterday broke dt and hitbox selection here is the issue:
double tap is DRASTICALLY inconsistent, hitboxes are broken, it starts missing WAY more

I don't know what it was maybe a offset or maybe something broke but please fix

**Comment by 0x000cb** [comment]
Can u show it on video? (Double tap don't work on matchmaking/wingman)

**Comment by SadSonic** [comment]
I'm playing in community servers I tried in 5 still didn't fix I can't really record a video I will have to first my words (no it's not a config issue)

1. I was using the day before the same config and it was fast great and hitting p
2. After that day I was going to play normally and I noticed that dt wasn't working so I thought safe point broke so I disabled 
3. After turning off safe point it RARELY SOMETIMES it double tapped but when it did the second shot always missed or always did 8 or a low damage 
4. Turning on safe point again so it doesn't miss it still misses for no reason and it does 8 damage sometimes for no reason even though my mom damage for visible is 41 
Hope this helps

**Comment by 0x000cb** [comment]
1. Maybe smth changed in engine. Idk.
2, 3. Perhaps you played on the same server, in which something inside changed. Try to check it not only on this server. Also try changing the configuration.
4. Minimum damage in OTC is not static.

**Comment by SadSonic** [comment]
1. Most probably
2. I played in different servers all the same. And my config was good I don't see any other reason to start doing that then csgo
3. I know but it wasn't doing this before

**Comment by SadSonic** [comment]
The new csgo update seems like fixed the problems I said before so all good.
