### ISSUE TITLE
Game crash after 1 game

### ISSUE THREAD

**Issue by flodes80** [0x000cb/otc#48]
Hi,

The dll works well for 1 game but it crash after when I'm loading a new game.
I have to restart the game.

I tried your recommendations about enabling multi core rendering and set dx9 option on launch etc ...

But it's still crashing after a game, very strange

Thanks for your help

**Comment by 0x000cb** [comment]
Hello. I’ll try to figure out what’s wrong.

**Comment by SadSonic** [comment]
Thank you I appreciate that :)

**Comment by 0x000cb** [comment]
Hello again. 
We tested OTC along and across but did not find such a problem. Do you use an addon?

**Comment by 0x000cb** [comment]
I do not see an answer for more than 2 days. 
-------
Closed.  
-------
(Reopen when describe the problem in more detail)
