### ISSUE TITLE
Detected

### ISSUE THREAD

**Issue by xXTOO-HARDXx** [0x000cb/otc#49]
Hello,

How "undetected" is this source? What needs to be done to make it undetected if that is the case.

Thanks, James.

**Comment by 0x000cb** [comment]
Hello. 
**We make no warranties regarding "Undetected"**. (For this reason, it is not specified in README. )

To circumvent VAC, developers typically use: **Protectors** / **JunkInjectors**.

**In no way can I guarantee you that this will help, all that you do is solely at your discretion.**
