### ISSUE TITLE
крашит при инжекте

### ISSUE THREAD

**Issue by noahmontelli** [0x000cb/otc#5]

**Comment by AnimeniacSimey** [comment]
Мисля, че той разбира. Вероятно го поправя сега.

**Comment by x001sys** [comment]
how to update offsets? help plz

**Comment by playday3008** [comment]
In `SegmentUtils.h` offsets

**Comment by x001sys** [comment]
yeah, but where can i found those offsets?

**Comment by x001sys** [comment]
> yeah, but where can i found those offsets?

and which offsets correspond to each value

**Comment by playday3008** [comment]
https://github.com/Akandesh/blazedumper
https://github.com/frk1/hazedumper
but i don't know how you can do it

**Comment by x001sys** [comment]
> https://github.com/Akandesh/blazedumper
> https://github.com/frk1/hazedumper
> but i don't know how you can do it

let's wait for the creator to update it

**Comment by playday3008** [comment]
ok, time to chill

**Comment by 0x000cb** [comment]
С новым обновлением все поправлю. Ожидайте.

**Comment by playday3008** [comment]
Уииии
