### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by toika32** [0x000cb/otc#50]
Works well with legit but crashes when using rage.
Tried: with and without -disable_d3d9ex, all graphics settings, clearing temp, verifying game files

**Comment by 0x000cb** [comment]
Hello. 
Under what conditions does a crash occur? Do you use an addon?

**Comment by toika32** [comment]
Without addon. It crashes on rage mode (when enemy is shootable), legit mode works perfectly. I think its problem with my pc.

**Comment by 0x000cb** [comment]
Why you think so?

**Comment by 0x000cb** [comment]
I do not see an answer for more than 2 days. 
-------
Closed.  
-------
(Reopen when describe the problem in more detail)
