### ISSUE TITLE
Im pretty sure u need an update

### ISSUE THREAD

**Issue by Pajo6** [0x000cb/otc#52]
Wh glitches, sometimes works sometimes not, constant misses

**Comment by Pajo6** [comment]
Like no cap, ragebot misses 75% off shots

**Comment by DoxyPS** [comment]
Not completely sure if im correct but attempt to use an addon resolver or the built in "Pitch Resolver" below auto fire and silent aim.

**Comment by 0x000cb** [comment]
"Ragebot misses 75% shots" - interesting statistic but probably it's cfg issue. 
"Wh glitches" - if you play on mm/wingman you should know about wh rip positions. It's not only for ot, it's literally for every sofrware.
"No cap" - If you talk about fakeduck, it's not working on mm/wingman.
