### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by sonsixd** [0x000cb/otc#53]
I get this error compiling the source 
3>LINK : fatal error LNK1181: cannot open input file 'libs\objects\HookLib.obj'
3>Done building project "OTC.vcxproj" -- FAILED.

**Comment by sonsixd** [comment]
I did not change nothing in the source and cloned the source directly from the git link

**Comment by 0x000cb** [comment]
This error occurs if you cloned a regular archive, and only after that did the command. (Example: https://youtu.be/BDKxzSQg36o). 

Possible solution: 
Take a ready-made obj (https://anonfile.com/34gbGctfo0/builded_rar), and move it to libs.

**Comment by sonsixd** [comment]
does it need to be updated or its fine with the obj in the anonfile
