### ISSUE TITLE
Menu doesn't render

### ISSUE THREAD

**Issue by KevinRommens** [0x000cb/otc#58]
I have done everrything I could to fix it (different injectors and help that you posted in the description) but the menu still doesn't render for me.
EDIT: OTC doesn't seem to work on the Texture Streaming Beta that CS:GO has. Please make it work on there as well otherwise i can't play, thanks.

**Comment by jalex45** [comment]
doesn't matter, I tried disabling texture streaming and injecting but it still doesn't load and crashes,
the process hacker output creates a werfault.exe and a gray csgo.exe processes which disappear after several minutes.

**Comment by KevinRommens** [comment]
> doesn't matter, I tried disabling texture streaming and injecting but it still doesn't load and crashes,
> the process hacker output creates a werfault.exe and a gray csgo.exe processes which disappear after several minutes.
> EDIT: FIXED! Go to Steam and change your beta to no beta/don't join any and it must be fixed. Close this thread.

Your edit literally just said what fix I have suggested for it. You're most likely braindead.

**Comment by 0x000cb** [comment]
The problem is that OTC cannot find the signature because the byte has changed. When texture filtering exits beta mode, I will update OTC to solve this problem.

(@KevinRommens Don't be stupid by creating such a title issue.)
