### ISSUE TITLE
otc.sln doesnt load correctly (visual studio 2019)

### ISSUE THREAD

**Issue by ixfit** [0x000cb/otc#60]
i am trying to build it myself so i can add more functions to it but every time i try to open the .sln in visual studio it says that it couldnt find the file from the directory  
C:\Users\my user\Desktop\otc-master\OTC\libs\libs\Zydis\msvc\zydis\Zydis.vcxproj
but from on 
C:\Users\my user\Desktop\otc-master\OTC\libs\libs
its empty, do you have those files somewhere so i can build it?

**Comment by YanderewareDev** [comment]
You need to download repository using git, `git clone https://github.com/0x000cb/otc.git && cd otc && git submodule update --init --recursive`

**Comment by 0x000cb** [comment]
@YanderewareDev Thx for solve. Closed.
