### ISSUE TITLE
Legit Bot doesn't work

### ISSUE THREAD

**Issue by degeneratehyperbola** [0x000cb/otc#63]
Thet's pretty much all, no function in legit bot does work

**Comment by 0x000cb** [comment]
Show vid.

**Comment by mazmamad** [comment]
work verry well but no silent ai,m so u can't use pistol and awp or it look like aimbot magnet obv

**Comment by degeneratehyperbola** [comment]
It seems to be fixed in the last update (don't know if that was csgo update or cheat's). Sorry for not recording a vid, wasn't able to.

**Comment by atxtn** [comment]
Everything works fine for me. Thank you developer for ur precious time :)
