### ISSUE TITLE
stuck loader

### ISSUE THREAD

**Issue by mazmamad** [0x000cb/otc#67]
when i inject the otc its stuck at "| [~] Filling the dependency table... (~7-15 sec)" 

the dll was fine before i restart game ..

i was restart windows tho and still stuck | [~] Filling the dependency table... (~7-15 sec)

**Comment by 0x000cb** [comment]
Hmmmmmmmmmmmmmmmm. Why loader stuck? Maybe bcoz filling table? Hmmmmmmmm.

**Comment by atxtn** [comment]
It’s not stuck, you gotta press the Insert key on your keyboard for menu to show.
