### ISSUE TITLE
CSGO Crashes on save/load config in a server with a config already loaded

### ISSUE THREAD

**Issue by hi1222222222** [0x000cb/otc#68]
I'm pretty sure it's not your ability to fix this, but CSGO will crash when you save or load a config in a server.

Also, for updating m_signatures, what option do you choose for sigmaker? I'm quite new to reverse engineering, so I am not that great with IDA. I can get my way around, I'm just a bit confused.

**Comment by 0x000cb** [comment]
I success load/save config on server. Idk wdym. 

client_panorama.dll -> Ida SigMaker plugin.

**Comment by hi1222222222** [comment]
Probably an issue with my hardware or smth.

I meant for actually getting the sigs, because i can go to the plugin menu, and get to the sigmaker menu, but what button do you press to actually get/go to the signatures? Sorry if I'm bothering.

**Comment by atxtn** [comment]
Everything is running fine, idk wtf y’all got going on.
