### ISSUE TITLE
Errors on Build

### ISSUE THREAD

**Issue by MrMuyV2** [0x000cb/otc#69]
I only get errors if i try do build the otc 

https://prnt.sc/sphx7x

Can someone help me :D

**Comment by 0x000cb** [comment]
Seems like you don't include segmentframework, or remove links from segmentframework.

**Comment by MrMuyV2** [comment]
ok but i just copy paste the new segmentframework because of the update

**Comment by 0x000cb** [comment]
git cmd: git pull.

**Comment by MrMuyV2** [comment]
what?
