### ISSUE TITLE
When are we getting an update?

### ISSUE THREAD

**Issue by AnimeniacSimey** [0x000cb/otc#7]
Sorry I was just wondering when we were getting an update... I'm really impatient, sorry!

**Comment by billythejew456** [comment]
or you could just do it your self the new offsets are probably on uc

**Comment by cptmacp** [comment]
Jesus christ
you leechers never appreciate free stuff, for real 

let the dev do his work and wait for the update 
it's not like he is entitled to give an ETA nor release an update ( totally on him if he wants to fix the cheat or not ) 

unlike f2c users who don't have life and cry and whine about free stuff, the dev has a LIFE 
so just calm down and wait for update.

stop spamming the issues section with a useless post such as this 

this is not an issue regarding the repository" OTC" 
this is an issue regarding you son.

**Comment by AnimeniacSimey** [comment]
Yes, and that makes you all high and mighty? You like being the little white knight? Discriminating against an entire group of people just because they don't want or can't pay for cheats? Chill, and fuck off.

**Comment by cptmacp** [comment]
@AnimeniacSimey I am not pretending to be anything
if you cant respect space and efforts of dev
you are no less than a leecher on the internet

as I said earlier, the issue you made on this repository is not regarding " OTC "
but your personal queries, if you fail to understand that, then you don't understand  Github and how it works.

and coming over free stuff, there is ratpoision and infinity which you can use if you can't afford paid cheats , simple as that.


and what part of my reply makes me " high and mighty "?  do explain that in fact, nothing I said was wrong.

discrimination what? telling f2c uses to stop making useless issue post on dev's git?
let along they spam on subreddit and forums? is that too much to ask, that you people annoy devs are other users here as well now. 

i am chill and i don't care for f2c 
actually it's you who is not calm 

https://github.com/0x000cb/otc/issues/4#issuecomment-605298289

when dev said to wait , you still have to make another issue post .

**Comment by pieromqwerty** [comment]
> Yes, and that makes you all high and mighty? You like being the little white knight? Discriminating against an entire group of people just because they don't want or can't pay for cheats? Chill, and fuck off.

jesus christ fuck off you skid. for one, this is github, not fucking reddit. issues are meant for issues being had in the code, not whining about updates for an open source cheat. as said by @cptmacp please fuck off and go cry to your mommy....

**Comment by AnimeniacSimey** [comment]
"Fuck off and go cry to your mommy"? That's so unbelievably original and creative. I applaud your genius and ability to absolutely destroy people. Seriously, what are you, 12?

**Comment by pieromqwerty** [comment]
> "Fuck off and go cry to your mommy"? That's so unbelievably original and creative. I applaud your genius and ability to absolutely destroy people. Seriously, what are you, 12?

You wouldn't know originality since you're the dictionary definition of a skid. Also, your csgo cheat doesn't work at all, doesn't even open lol.

**Comment by AnimeniacSimey** [comment]
a) And you're not? If you arent a skid, why are you here?? b) That's real relevant, honestly. If you're not a skid, you are the poster child of the keyboard warrior. A cheat loader that was written more than half of a year ago has nothing to do with this thread or even cheat, you are just looking for anything that could possibly make me look worse in a pointless internet argument, and all you do is make yourself look retarded. c) Fuck off. This isnt your argument to begin with.

**Comment by pieromqwerty** [comment]
1. I'm not a skid, I've been programming for more than 4 years.
2. I'm here because I wanted to contribute and help out on github. That is how it works, people help each other out when it comes to open source.
3. Btw, I was bringing up that 'loader' (a dll isn't a loader last time I checked) as an example to call you a skid who doesn't know what they're doing.
4. Last but not least, i'm not entering into any argument. I saw this issue and commented. Now, please screw off and stop getting mad that the head dev of OTC has other things going on in their life.

**Comment by AnimeniacSimey** [comment]
1. What funniest about all of this is that you have presumably been coding several languages for a few years, and you are pointlessly taking time and money out of your day to argue with a 14 year old online.

2. That's fair.

3. I dont have any repos even so much as  mentioning dlls. 

4. You entirely are. This whole argument was started by cptmacp, whom you directly quoted in your first message. I was not in any way mad and I'm perfectly aware that the dev who is experienced enough to write something like this has other things to do, presumably that actually contribute to their life. Lastly, this was not the "original 'dev' of OTC", they wrote the offset updater for it.

**Comment by pieromqwerty** [comment]
1. Dude, im a 17 year old with too much time on his hands.
2. K
3. Ahem:
- https://github.com/AnimeniacSimey/FloWare-Loader/blob/master/otc.dll (also, where tf did you get a 1.58mb dll???)
- https://github.com/AnimeniacSimey/very-important/blob/master/RxvanWare.dll
4. I meant the original cracker.

**Comment by cptmacp** [comment]
cmon guys lets keep it civilized.

I think AnimeniacSimey now understands what we all meant here.
we didn't mean any insult or making fun or so.

working on something without actual source is hard and if someone is working on it, we should let him do it and give him the time and space, there was nothing else I wanted to tell.
I hope everyone understand .

so if you agree on AnimeniacSimey , please close this issue, so that any other user who is browsing this repository doesn't have to see this unnecessary stuff.

Peace out.

**Comment by 0x000cb** [comment]
Stop it. No toxicity at least in the repository. The update is already in progress.

![image](https://user-images.githubusercontent.com/42978074/78086263-b6234780-73bd-11ea-8949-338d2c2b391d.png)
