### ISSUE TITLE
hooklib(unloaded) zydis(unloaded)

### ISSUE THREAD

**Issue by lilskeetr** [0x000cb/otc#71]
error 
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3073	The command "copy C:\Users\rodin\Desktop\OTC\Release\HookLib.lib C:\Users\rodin\Desktop\OTC\libs\libs\HookLib.lib
copy C:\Users\rodin\Desktop\OTC\libs\libs\HookLib\HookLib\Release\HookLib.pdb C:\Users\rodin\Desktop\OTC\libs\libs\HookLib.pdb
if not exist C:\Users\rodin\Desktop\OTC\libs\objects mkdir C:\Users\rodin\Desktop\OTC\libs\objects
copy C:\Users\rodin\Desktop\OTC\libs\libs\HookLib\HookLib\Release\HookLib.obj C:\Users\rodin\Desktop\OTC\libs\objects\HookLib.obj
copy C:\Users\rodin\Desktop\OTC\libs\libs\Zydis\msvc\bin\ReleaseX86\Zydis.lib C:\Users\rodin\Desktop\OTC\libs\libs\Zydis.lib
copy "C:\Users\rodin\Desktop\OTC\libs\libs\Zydis\msvc\zydis\obj\Zydis-Win32-Release MT\Zydis.pdb" "C:\Users\rodin\Desktop\OTC\libs\libs\Zydis.pdb"
:VCEnd" exited with code 1.	OTC	C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets	139

**Comment by Kalegger** [comment]
* 🔶 **How clone this repository ?**
     * ``` git clone https://github.com/0x000cb/otc.git  && cd otc && git submodule update --init --recursive ```

**Comment by l3Sweayy** [comment]
i have the same problem

**Comment by 0x000cb** [comment]
I will close all such problems without answering them. 
**The answer was sent by Kalegger.**

If you do not know how to clone a repository, do not try to do it. 
Watch the video on YouTube. (Tutorial)
**If you continue to flood, you will be blocked.**
