### ISSUE TITLE
Chams attachments

### ISSUE THREAD

**Issue by MrMuyV2** [0x000cb/otc#75]
I guess chams attachments does not work :D can you fix it? :D

**Comment by 0x000cb** [comment]
Can you show it on vid?

**Comment by MrMuyV2** [comment]
Sure wait

**Comment by MrMuyV2** [comment]
Here :D

**Comment by MrMuyV2** [comment]
https://youtu.be/UxVzqUbrSk8

**Comment by MrMuyV2** [comment]
https://www.mediafire.com/file/pxv3rtioln0sqak/Counter-strike__Global_Offensive_2020.05.29_-_23.21.35.02.mp4/file

**Comment by 0x000cb** [comment]
Yeah. Seems like broken. I'll try to figure out what's wrong.
