### ISSUE TITLE
Sliding while legit hacking

### ISSUE THREAD

**Issue by WilliamJiH** [0x000cb/otc#76]
Hi, I found myself sliding in the killer replay while I'm legit hacking. I viewed myself in third person and  my feet are moving, but in the killer replay my feet are sliding. Why?

**Comment by 0x000cb** [comment]
https://github.com/0x000cb/otc/issues/64

**Comment by DoxyPS** [comment]
Client side, had a friend into comp with me and asked him about it. He only saw normal movement and with legit aa on he saw minimal sliding. None noticable my overwatch if your sceptical.
