### ISSUE TITLE
There Are Missing Files

### ISSUE THREAD

**Issue by l3Sweayy** [0x000cb/otc#77]
C:\Users\lance\Desktop\otc-master\OTC\libs\libs\HookLib\HookLib\HookLib.vcxproj : error  : The project file could not be loaded. Could not find a part of the path 'C:\Users\lance\Desktop\otc-master\OTC\libs\libs\HookLib\HookLib\HookLib.vcxproj'.  C:\Users\lance\Desktop\otc-master\OTC\libs\libs\HookLib\HookLib\HookLib.vcxproj

C:\Users\lance\Desktop\otc-master\OTC\libs\libs\Zydis\msvc\zydis\Zydis.vcxproj : error  : The project file could not be loaded. Could not find a part of the path 'C:\Users\lance\Desktop\otc-master\OTC\libs\libs\Zydis\msvc\zydis\Zydis.vcxproj'.  C:\Users\lance\Desktop\otc-master\OTC\libs\libs\Zydis\msvc\zydis\Zydis.vcxproj

and there is this

1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(139,5): error MSB3073: The command "copy C:\Users\lance\Desktop\otc-master\OTC\Release\HookLib.lib C:\Users\lance\Desktop\otc-master\OTC\libs\libs\HookLib.lib
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(139,5): error MSB3073: copy C:\Users\lance\Desktop\otc-master\OTC\libs\libs\HookLib\HookLib\Release\HookLib.pdb C:\Users\lance\Desktop\otc-master\OTC\libs\libs\HookLib.pdb
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(139,5): error MSB3073: if not exist C:\Users\lance\Desktop\otc-master\OTC\libs\objects mkdir C:\Users\lance\Desktop\otc-master\OTC\libs\objects
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(139,5): error MSB3073: copy C:\Users\lance\Desktop\otc-master\OTC\libs\libs\HookLib\HookLib\Release\HookLib.obj C:\Users\lance\Desktop\otc-master\OTC\libs\objects\HookLib.obj
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(139,5): error MSB3073: copy C:\Users\lance\Desktop\otc-master\OTC\libs\libs\Zydis\msvc\bin\ReleaseX86\Zydis.lib C:\Users\lance\Desktop\otc-master\OTC\libs\libs\Zydis.lib
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(139,5): error MSB3073: copy "C:\Users\lance\Desktop\otc-master\OTC\libs\libs\Zydis\msvc\zydis\obj\Zydis-Win32-Release MT\Zydis.pdb" "C:\Users\lance\Desktop\otc-master\OTC\libs\libs\Zydis.pdb"
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(139,5): error MSB3073: :VCEnd" exited with code 1.
1>Done building project "OTC.vcxproj" -- FAILED.

**Comment by NetnetZ** [comment]
clone the repo instead of download
use this command `git clone https://github.com/0x000cb/otc.git && cd otc && git submodule update --init --recursive`
