### ISSUE TITLE
Missing Files After Clone

### ISSUE THREAD

**Issue by jackhoff8347** [0x000cb/otc#78]
cannot open input file 'libs\objects\HookLib.obj' | nor can it open HookLib.lib or Zydis.lib but they all seem to be in the project just not in the physical files
-
i used "git clone https://github.com/0x000cb/otc.git && cd otc && git submodule update --init --recursive" ran as admin all other files and libs are here just not thoes

**Comment by jackhoff8347** [comment]
someone released a fix <https://github.com/0x000cb/otc/pull/80> but im noticing the submodules also have their own submodules and thoes dont seem to be installing like "Zycore"

**Comment by 0x000cb** [comment]
Use build configuration: "First release".

**Comment by jackhoff8347** [comment]
i did same issue
