### ISSUE TITLE
Resolver is broken.

### ISSUE THREAD

**Issue by Sasaki178** [0x000cb/otc#79]
So, there is the resolver which is completely broken. Its not that problem which make the cheat no longer to be used but its kinda annoying.So if u can improve the resolver everyone gonna be grateful to you i think. :) But if u can't do it, its not problem it was just an idea. 👍

**Comment by jackhoff8347** [comment]
it works fine according to the last build i have my own issue but thats unrelated to its actual code

**Comment by Sasaki178** [comment]
As i said, its not make the cheat no longer be used. So the resolver is working but its very bad. You can't tap someone who has a little better anti-aim.

**Comment by DoxyPS** [comment]
@Sasaki178 You could refer to using an OTC addon (not suggesting any so do research) but in some cases the cheat is better without a resolver enabled. You could go baim mode which 90% of the time will not hit fakes unless only peoples fakes are being shown.

**Comment by DoxyPS** [comment]
Also the resolver is not broken, just outdated and not that good/

**Comment by Sasaki178** [comment]
> Also the resolver is not broken, just outdated and not that good/
yes, that's what i meant sorry if i was misunderstood.
