### ISSUE TITLE
Problem with shooting.

### ISSUE THREAD

**Issue by KevinRommens** [0x000cb/otc#81]
Sometimes when im too close to an enemy the aimbot  doesn't  shoot. Please try to look into it, i have it very infrequently so i don't really care, but when it happens it's really annoying.

**Comment by 0x000cb** [comment]
Possible caused by cfg. Try setup hitchance.

**Comment by KevinRommens** [comment]
Hitchance is 65%

Op za 30 mei 2020 om 20:39 schreef 0x000cb <notifications@github.com>:
