### ISSUE TITLE
Missing Files After Clone

### ISSUE THREAD

**Issue by jackhoff8347** [0x000cb/otc#82]
#78 i used your build "First Release" and it has the same issue :) could talk before closing the issue <3

**Comment by 0x000cb** [comment]
Can you show clone & build at vid?

**Comment by jackhoff8347** [comment]
sure 1 sec

**Comment by jackhoff8347** [comment]
when it uploads: https://youtu.be/rMOtr8pkEbA

**Comment by 0x000cb** [comment]
Seems like file exists but linker can't provide him. I will try re-configure building.

**Comment by 0x000cb** [comment]
I forgot to add First Release to the active configuration. Try replacing vcxproj and rebuilding the project.

https://anonfiles.com/f6z9S132o2/OTC_vcxproj

**Comment by jackhoff8347** [comment]
still happens

**Comment by 0x000cb** [comment]
Can we move to discord? (Don't want flood)

**Comment by jackhoff8347** [comment]
sure https://discord.gg/rXMURC

**Comment by 0x000cb** [comment]
Caused: https://media.discordapp.net/attachments/716383662425505814/716387124034797678/unknown.png

Possible fix: Create objects folder.

cursed resolved.
![imgonline-com-ua-Resize-Ak9ReuFGbvA](https://user-images.githubusercontent.com/42978074/83338643-08ee8200-a2cf-11ea-9cd3-775a69d5c0c7.png)
