### ISSUE TITLE
ощшибка

### ISSUE THREAD

**Issue by NoysCheats** [0x000cb/otc#84]
как исправить ошибку? C:\otc-master\OTC\libs\libs\Zydis\msvc\zydis\Zydis.vcxproj : error  : Не удалось найти проект C:\otc-master\OTC\libs\libs\Zydis\msvc\zydis\Zydis.vcxproj.

**Comment by vianove13** [comment]
git submodule update --init --recursive

**Comment by guttir14** [comment]
git submodule update --init --recursive
