### ISSUE TITLE
When I get a unexpected death or most likely when I die to a headshot, if I'm on legitbot I crash and CSGO close.

### ISSUE THREAD

**Issue by jalex45** [0x000cb/otc#88]

**Comment by winxpqq955** [comment]
Disable Backtrack

**Comment by TooneyTurkey** [comment]
just dont legit bot pow problem solved

**Comment by KevinRommens** [comment]
i have this a lot too, i dont knoiw what is causing it

**Comment by pyrussian69** [comment]
hi pokey

**Comment by jalex45** [comment]
> Hello.
> 
> * In what mode was this problem observed? (MatchMaking / Wingman / Community / SelfServer).
> * How often do you encounter this problem?
> * What is your PC configuration?
> * Has this problem been observed previously?
> * Do you use csgo beta builds?
> 
> Any additional information will be crucial in order to solve the problem.

Someone said 'Disable backtrack' and it worked, you could fix the backtrack if possible.

**Comment by 0x000cb** [comment]
Ok...
