### ISSUE TITLE
Seems like CSGO just patched the cheat. 

### ISSUE THREAD

**Issue by atxtn** [0x000cb/otc#91]
I tried injecting the dll after the recent update and got this message. Also when I try to close the game everything freezes, ctrl + alt + del to open task manager won't work either so I had to restart my PC. 

![error](https://user-images.githubusercontent.com/66048579/83720286-64d24700-a5fe-11ea-864a-e0fa10e3aaa9.png)

**Comment by TooneyTurkey** [comment]
yep got the same thing

**Comment by hyperx47** [comment]
lol me too

**Comment by atxtn** [comment]
Ya'll also had to ctrl + alt + del to restart ur PCs ?

**Comment by hyperx47** [comment]
yeah or the screen just froze

**Comment by 0x000cb** [comment]
Nah. Just signature changed. Fix coming soon.

**Comment by atxtn** [comment]
ty boss <3

**Comment by 0x000cb** [comment]
Or smth going wrong. hmm.

![image](https://user-images.githubusercontent.com/42978074/83722235-4e9ba980-a645-11ea-8bf0-beb942e24856.png)

**Comment by 0x000cb** [comment]
![image](https://user-images.githubusercontent.com/42978074/83722726-32e4d300-a646-11ea-8cc9-242c9bba498b.png)

ok...

**Comment by Kostenko16** [comment]
what does this mean

**Comment by HowToMakeFaceitAB** [comment]
> ![image](https://user-images.githubusercontent.com/42978074/83722726-32e4d300-a646-11ea-8cc9-242c9bba498b.png)
> 
> ok...

Explain @0x000cb

**Comment by HowToMakeFaceitAB** [comment]
> Or smth going wrong. hmm.
> 
> ![image](https://user-images.githubusercontent.com/42978074/83722235-4e9ba980-a645-11ea-8bf0-beb942e24856.png)

Add me discord Saitama#7564

**Comment by 0x000cb** [comment]
It's mean "csgo don't load client_panorama.dll". So maybe possible fix just replace client_panorama to client.

**Comment by HowToMakeFaceitAB** [comment]
Whatt? Just add me discord Saitama#7564

**Comment by 0x000cb** [comment]
![image](https://user-images.githubusercontent.com/42978074/83723967-28c3d400-a648-11ea-8062-a280f1da15d3.png)

Update coming soon.

**Comment by atxtn** [comment]
> ![image](https://user-images.githubusercontent.com/42978074/83722726-32e4d300-a646-11ea-8cc9-242c9bba498b.png)
> 
> ok...

what's wrong with it?

**Comment by 0x000cb** [comment]
Update already in repository. Just redownload dll.
