### ISSUE TITLE
{New CSGO Update}

### ISSUE THREAD

**Issue by CyberKiller1024** [0x000cb/otc#92]
----------- INFO ----------
Layer: 1.
Caused: Can't find offset. Signature: 55 8B EC 83 E4 F8 83 EC 70 6A 58.
----------------------------
Global variables: 
-----------------------------------------------------------
[SEGMENT] Module: 0x57D60000
[SEGMENT] Allocation: 0x301B0000
-----------------------------------------------------------

**Comment by 0x000cb** [comment]
![image](https://user-images.githubusercontent.com/42978074/83724221-8d7f2e80-a648-11ea-9437-ce1dc8f6cfae.png)

Already fixed.

**Comment by HowToMakeFaceitAB** [comment]
> ![image](https://user-images.githubusercontent.com/42978074/83724221-8d7f2e80-a648-11ea-9437-ce1dc8f6cfae.png)
> 
> Already fixed.

Update time?

**Comment by CyberKiller1024** [comment]
Kindly Update ASAP

**Comment by atxtn** [comment]
Stop being impatience and annoying, he already said coming soon... SOON means in the very near future.

**Comment by CyberKiller1024** [comment]
Thank You!

**Comment by 0x000cb** [comment]
Update already in repository. Just redownload dll.

**Comment by Cride20** [comment]
Can you please post the signatures you changed?

**Comment by 0x000cb** [comment]
I'm not change signatures. Just change client_panorama to client.

https://github.com/0x000cb/otc/commit/f02f2ef91ab08ea2e2865eb1c282484a8acbb952
