### ISSUE TITLE
When i press legit aimbot key and if i do not see the enemy then my crosshair magnetized to the random point on screen.

### ISSUE THREAD

**Issue by UXR7b** [0x000cb/otc#93]

**Comment by 0x000cb** [comment]
Accepted. Expect verification.

**Comment by UXR7b** [comment]
and this issue work when the enemy leaves my fov

**Comment by ixfit** [comment]
why would u ever have ur legitbot on such a big aimlock, just use rage instead

**Comment by 0x000cb** [comment]
Your sight is magnetized to the nearest enemy. You can turn on wh and check it out.
