### ISSUE TITLE
fix otc

### ISSUE THREAD

**Issue by ixfit** [0x000cb/otc#97]
Hello, i am not sure if you are a busy man but i would like to learn how to fix the code from otc after the updates and im trying to find someone that can teach me this, if you have time pls add me on discord ixfit#2490 if not, just decline this "issue"

**Comment by KevinRommens** [comment]
you can just dig a little deeper and find that 0x000cb updates the DLL itself here.

**Comment by 0x000cb** [comment]
You just need to learn the basics of C++, practice reverse engineering and know very little about how the cheat works (If you want just fix otc). 
Everything else will come with experience. 
_____
You can see how i fix OTC in the commit history.
